#!/usr/bin/env python3
"""Generate the shared patcher data for both the C and Java builds.

The Windows patcher is C/SDL2 and the Android patcher is pure Java. Neither
should hand-copy patch constants, because a silent drift between the two would
produce different patched ROMs from the same input. Both therefore compile
against data generated here from one authoritative plan.

Sources:
  tools/patch_sources/hard_mode_plan.json  public constants only
  tools/patch_sources/font8x8.txt          original bitmap font

Outputs:
  src/core/pit_patch_data.h                        C header
  android/.../patcher/PatchData.java               Java class

Scales are emitted as exact integer numerators and denominators rather than
doubles. Rounding then becomes integer arithmetic in all three languages, so
C, Java and tools/make_data_profile.py cannot disagree on a value that lands
exactly on a .5 boundary.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from fractions import Fraction
from pathlib import Path

FONT_FIRST = 0x20
FONT_LAST = 0x7E
GLYPH_W = 8
GLYPH_H = 8

BANNER = " *  Generated by port/tools/gen_patchplan.py -- do not edit by hand.  *"


def parse_font(path: Path) -> dict[int, list[str]]:
    glyphs: dict[int, list[str]] = {}
    for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        code = int(parts[0], 10)
        rows = parts[1:]
        if len(rows) != GLYPH_H:
            raise SystemExit(f"{path}:{lineno}: expected {GLYPH_H} rows, got {len(rows)}")
        padded = []
        for row in rows:
            if set(row) - {".", "#"}:
                raise SystemExit(f"{path}:{lineno}: bad row {row!r}")
            if len(row) > GLYPH_W:
                raise SystemExit(
                    f"{path}:{lineno}: row {row!r} is {len(row)} cells, max {GLYPH_W}")
            # Rows are written without trailing blanks and right-padded to the
            # full cell, so a glyph is 5x7 plus a 3px gap and one descender row.
            padded.append(row.ljust(GLYPH_W, "."))
        glyphs[code] = padded
    missing = [c for c in range(FONT_FIRST, FONT_LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit(
            f"{path}: missing glyphs for codepoints "
            + ", ".join(f"0x{c:02X}" for c in missing)
        )
    return glyphs


def row_bits(row: str) -> int:
    """Pack one row so that bit 7 is the leftmost pixel."""
    value = 0
    for col, cell in enumerate(row):
        if cell == "#":
            value |= 1 << (GLYPH_W - 1 - col)
    return value


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def java_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def scale_label(frac: Fraction) -> str:
    """Short exact display form, e.g. "x11/10" or "x2".

    Shown in the plan panel of both UIs. It is derived from the same Fraction
    the patch math uses, so the label cannot describe a different multiplier
    than the one applied.
    """
    if frac.denominator == 1:
        return f"x{frac.numerator}"
    return f"x{frac.numerator}/{frac.denominator}"


def build(plan: dict, glyphs: dict[int, list[str]]) -> tuple[str, str]:
    rom = plan["supported_rom"]
    target = plan["target"]
    transforms = plan["transforms"]
    fields = {f["name"]: f for f in target["fields"]}

    for t in transforms:
        if t["field"] not in fields:
            raise SystemExit(f"transform {t['field']!r} has no matching field")
    for name in fields:
        if not any(t["field"] == name for t in transforms):
            raise SystemExit(f"field {name!r} has no transform")

    header: list[str] = []
    add = header.append
    add("/*")
    add(" * Patcher data shared by the Windows and Android builds.")
    add(BANNER)
    add(" *")
    add(" * Every value below is a public constant: an expected hash, a NitroFS")
    add(" * path, a record stride, field offsets recovered from the decompiled")
    add(" * BattleEnemyStatRecord, and multipliers. No retail ROM bytes, names or")
    add(" * stats are stored here. The patcher reads those from the user's ROM.")
    add(" */")
    add("#ifndef PIT_PATCH_DATA_H")
    add("#define PIT_PATCH_DATA_H")
    add("")
    add("#define PIT_PLAN_ID          " + c_string(plan["id"]))
    add("#define PIT_PLAN_NAME       " + c_string(plan["name"]))
    add("#define PIT_PLAN_VERSION    " + c_string(plan["version"]))
    add("")
    # These are prefixed PIT_PLAN_ROM_ rather than PIT_ROM_ because pit_rom.h
    # already defines PIT_ROM_SHA1. Both describe the same EUR ROM, but two
    # macros with one meaning invites a silent mismatch later.
    add("#define PIT_PLAN_ROM_SHA1      " + c_string(rom["sha1"]))
    add("#define PIT_PLAN_ROM_TITLE     " + c_string(rom["title"]))
    add("#define PIT_PLAN_ROM_GAME_CODE " + c_string(rom["game_code"]))
    add("#define PIT_PLAN_ROM_SIZE      " + str(rom["size"]) + "u")
    add("#define PIT_PLAN_ROM_BADGE     " + c_string(rom["badge"]))
    add("")
    add("#define PIT_TARGET_PATH     " + c_string(target["nitrofs_path"]))
    add(f"#define PIT_RECORD_SIZE     {target['record_size']}u")
    add(f"#define PIT_RECORD_COUNT    {target['record_count']}u")
    add("")
    add("#define PIT_FIELD_COUNT     "
        f"{len(target['fields'])}u")
    add("#define PIT_TRANSFORM_COUNT " + f"{len(transforms)}u")
    add("")

    add("typedef struct {")
    add("    const char *name;")
    add("    const char *label;")
    add("    unsigned int offset;")
    add("} pit_plan_field;")
    add("")
    add("static const pit_plan_field PIT_PLAN_FIELDS[PIT_FIELD_COUNT] = {")
    for f in target["fields"]:
        add("    { " + c_string(f["name"]) + ", " + c_string(f["label"])
            + f", {f['offset']}u }},")
    add("};")
    add("")

    add("typedef struct {")
    add("    const char *field;")
    add("    const char *label;")
    add("    const char *scale_text;  /* display form of num / den */")
    add("    unsigned int num;  /* scale is exactly num / den */")
    add("    unsigned int den;")
    add("    unsigned int min_value;")
    add("    unsigned int max_value;")
    add("} pit_plan_transform;")
    add("")
    add("static const pit_plan_transform")
    add("    PIT_PLAN_TRANSFORMS[PIT_TRANSFORM_COUNT] = {")
    for t in transforms:
        frac = Fraction(str(t["scale"]))
        add("    { " + c_string(t["field"]) + ", " + c_string(t["label"]) + ", "
            + c_string(scale_label(frac))
            + f", {frac.numerator}u, {frac.denominator}u, "
            + f"{t['min']}u, {t['max']}u }},")
    add("};")
    add("")
    add("/* Original 8x8 font. Bit 7 of each byte is the leftmost pixel. */")
    add(f"#define PIT_FONT_GLYPH_COUNT {len(glyphs)}u")
    add("static const unsigned char PIT_FONT8X8[PIT_FONT_GLYPH_COUNT][8] = {")
    for code in range(FONT_FIRST, FONT_LAST + 1):
        rows = glyphs[code]
        packed = ", ".join(f"0x{row_bits(r):02X}" for r in rows)
        label = "space" if code == 0x20 else chr(code)
        add(f"    {{ {packed} }},  /* {code:02X} {label} */")
    add("};")
    add("")
    add("#endif /* PIT_PATCH_DATA_H */")
    header_text = "\n".join(header) + "\n"

    # Java
    j: list[str] = []
    jadd = j.append
    jadd("/*")
    jadd(" * Patcher data shared by the Windows and Android builds.")
    jadd(BANNER)
    jadd(" */")
    jadd("package com.partnersintime.patcher;")
    jadd("")
    jadd("public final class PatchData {")
    jadd("    private PatchData() {")
    jadd("    }")
    jadd("")
    jadd("    public static final String PLAN_ID = " + java_string(plan["id"]) + ";")
    jadd("    public static final String PLAN_NAME = " + java_string(plan["name"]) + ";")
    jadd("    public static final String PLAN_VERSION = "
          + java_string(plan["version"]) + ";")
    jadd("")
    jadd("    public static final String ROM_SHA1 = " + java_string(rom["sha1"]) + ";")
    jadd("    public static final String ROM_TITLE = " + java_string(rom["title"]) + ";")
    jadd("    public static final String ROM_GAME_CODE = "
          + java_string(rom["game_code"]) + ";")
    jadd("    public static final String ROM_BADGE = " + java_string(rom["badge"]) + ";")
    jadd(f"    public static final int ROM_SIZE = {rom['size']};")
    jadd("")
    jadd("    public static final String TARGET_PATH = "
          + java_string(target["nitrofs_path"]) + ";")
    jadd(f"    public static final int RECORD_SIZE = {target['record_size']};")
    jadd(f"    public static final int RECORD_COUNT = {target['record_count']};")
    jadd("")
    jadd("    public static final String[] FIELD_NAMES = {")
    for f in target["fields"]:
        jadd("        " + java_string(f["name"]) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final String[] FIELD_LABELS = {")
    for f in target["fields"]:
        jadd("        " + java_string(f["label"]) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final int[] FIELD_OFFSETS = {")
    jadd("        " + ", ".join(str(f["offset"]) for f in target["fields"]) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final int[] TRANSFORM_FIELD = {")
    for idx, t in enumerate(transforms):
        jadd(f"        {target['fields'].index(fields[t['field']])},")
        del idx
    jadd("    };")
    jadd("")
    jadd("    public static final int[] TRANSFORM_NUM = {")
    jadd("        " + ", ".join(
        str(Fraction(str(t["scale"])).numerator) for t in transforms) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final int[] TRANSFORM_DEN = {")
    jadd("        " + ", ".join(
        str(Fraction(str(t["scale"])).denominator) for t in transforms) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final int[] TRANSFORM_MIN = {")
    jadd("        " + ", ".join(str(t["min"]) for t in transforms) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final int[] TRANSFORM_MAX = {")
    jadd("        " + ", ".join(str(t["max"]) for t in transforms) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final String[] TRANSFORM_LABEL = {")
    for t in transforms:
        jadd("        " + java_string(t["label"]) + ",")
    jadd("    };")
    jadd("")
    jadd("    /* Display form of TRANSFORM_NUM/TRANSFORM_DEN, e.g. \"x11/10\". */")
    jadd("    public static final String[] TRANSFORM_SCALE = {")
    for t in transforms:
        jadd("        " + java_string(scale_label(Fraction(str(t["scale"])))) + ",")
    jadd("    };")
    jadd("")
    jadd("    public static final int FONT_FIRST = " + str(FONT_FIRST) + ";")
    jadd("    public static final int FONT_GLYPHS = " + str(len(glyphs)) + ";")
    jadd("")
    jadd("    /* Row bytes for codepoints 0x20..0x7E. Bit 7 is the leftmost pixel. */")
    jadd("    public static final int[][] FONT8X8 = {")
    for code in range(FONT_FIRST, FONT_LAST + 1):
        packed = ", ".join(f"0x{row_bits(r):02X}" for r in glyphs[code])
        jadd("        {" + packed + "},")
    jadd("    };")
    jadd("}")
    java_text = "\n".join(j) + "\n"
    return header_text, java_text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--plan", type=Path,
                    default=Path("tools/patch_sources/hard_mode_plan.json"))
    ap.add_argument("--font", type=Path,
                    default=Path("tools/patch_sources/font8x8.txt"))
    ap.add_argument("--c-out", type=Path, default=Path("src/core/pit_patch_data.h"))
    ap.add_argument("--java-out", type=Path, default=Path(
        "android/app/src/main/java/com/partnersintime/patcher/PatchData.java"))
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero if the outputs would change")
    args = ap.parse_args()

    plan = json.loads(args.plan.read_text(encoding="utf-8"))
    glyphs = parse_font(args.font)
    header_text, java_text = build(plan, glyphs)

    if args.check:
        stale = []
        for path, text in ((args.c_out, header_text), (args.java_out, java_text)):
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path))
        if stale:
            print("out of date: " + ", ".join(stale))
            return 1
        print("generated data is up to date")
        return 0

    for path, text in ((args.c_out, header_text), (args.java_out, java_text)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
